### ISSUE TITLE
Installation of RHOCP cluster by using Redhat certified CNI like Calico/Cilium

### ISSUE THREAD

**Issue by shashank-6777** [redhat-partner-solutions/crucible#248]
### Feature description

Hi Team,

First of all thankyou for providing this robust automation to install openshift. As you know now some of third party CNI's like calico/cilium are present as certified operator by redhat, so is it possible if i choose to deploy my cluster with these CNI instead of OVN/SDN by using current inventory ?

### Required statements

- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by nocturnalastro** [comment]
It should be possible, It would be a case of adding custom manifests. Define `extra_manifests` in your inventory this is a list of dicts. The commit is [here](https://github.com/redhat-partner-solutions/crucible/commit/5060d66dc8ab461b83d47767edd48cdc980ecc37).
For instance I use it to see the manifests requires for LSO 
```yaml
    extra_manifests:
      - template: "{{ inventory_dir }}/manifests/{{ cluster_name }}/50-master-create-lvs-for-lso.yml.j2"
      - file: "{{ inventory_dir }}/manifests/{{ cluster_name }}/60-lv-for-lso.yml"
      - file: "{{ inventory_dir }}/manifests/{{ cluster_name }}/70-sc-for-lso.yml"
```
