### ISSUE TITLE
RHEL 9.1 + OCP 4.13.10 installation failed

### ISSUE THREAD

**Issue by shashank-6777** [redhat-partner-solutions/crucible#277]
### Bug description

Hi Team,

I am trying to install OCP 4.13.10 with 9.1 by using latest crucible framwork but my installation failed everytime, I found below two error on OCP failed nodes.

Can you please let me know how can i solve these issues. ?

### OpenShift version

other (provide in the description)

### Assisted Installer version

v2.12.1

### Relevant log output

```shell
**Error 1:-**

Oct 11 11:01:28 master-super1.nec.nfvi.localdomain next_step_runne[2488]: time="11-10-2023 11:01:28" level=info msg="Executing timeout [30 chronyc -n sources]" file="execute.go:39"
Oct 11 11:01:28 master-super1.nec.nfvi.localdomain next_step_runne[2488]: time="11-10-2023 11:01:28" level=error msg="Failed to get NTP sources" file="ntp_synchronizer.go:170" error="chronyc exited with non-zero exit code 1: \nchronyc: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by chronyc)\nchronyc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by chronyc)\n"
Oct 11 11:01:28 master-super1.nec.nfvi.localdomain next_step_runne[2488]: time="11-10-2023 11:01:28" level=error msg="Step execution failed (exit code -1): <ntp-synchronizer-475163b7>, command: <ntp_synchronizer>, args: <[{\"ntp_source\":\"172.90.12.210\"}]>. Output:\nstdout:\n\n\nstderr:\nchronyc exited with non-zero exit code 1: \nchronyc: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by chronyc)\nchronyc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by chronyc)\n\n" file="step_processor.go:110" request_id=1bbccc67-dce2-45e7-98ca-6199828dcb8f

```
```shell
**Error 2:-**

Oct 11 11:02:37 master-super1.nec.nfvi.localdomain next_step_runne[2488]: time="11-10-2023 11:02:37" level=error msg="Step execution failed (exit code 255): <installation-disk-speed-check-9ee10436>, command: <sh>, args: <[-c id=`podman ps --quiet --filter \"name=disk_performance\"` ; test ! -z \"$id\" || timeout 480.00 podman run --privileged --rm --quiet -v /dev:/dev:rw -v /var/log:/var/log -v /run/systemd/journal/socket:/run/systemd/journal/socket --name disk_performance registry.nec.nfvi.localdomain:5000/ocpmetal/assisted-installer-agent@sha256:6d782042debb951b202c80869f2dd30fffb9272010a46d77ea39ce8f6a862162 disk_speed_check '{\"path\":\"/dev/disk/by-path/pci-0000:04:00.0\"}']>. Output:\nstdout:\n{\"path\":\"/dev/disk/by-path/pci-0000:04:00.0\"}\n\nstderr:\nCould not get I/O performance for path /dev/disk/by-path/pci-0000:04:00.0 (fio exit code: 1, stderr: fio: io_u error on file /dev/disk/by-path/pci-0000: No space left on device: write offset=4194304, buflen=896\n)\n" file="step_processor.go:110" request_id=ce192de1-5656-4c65-84dc-2f5656822981
```
### Inventory file

```yaml
all:
  vars:
    ##################################
    # Assisted Install Configuration #
    ##################################
    # These options configure Assisted Installer and the resulting cluster
    # https://generator.swagger.io/?url=https://raw.githubusercontent.com/openshift/assisted-service/58a6abd5c99d4e41d939be89cd0962433849a861/swagger.yaml
    # See section: cluster-create-params

    # Cluster name and dns domain combine to give the cluster namespace that will contain OpenShift endpoints
    # e.g. api.clustername.example.lab, worker1.clustername.example.lab
    cluster_name: nec
    base_dns_domain: nfvi.localdomain

    # OpenShift version (4.6.16, 4.7.52, 4.8.43, 4.9.45, 4.10.37, 4.11.24, 4.12.31, or 4.13.10)
    openshift_full_version: 4.13.10

    # Virtual IP addresses used to access the resulting OpenShift cluster
    api_vip: 172.90.12.242 # the IP address to be used for api.clustername.example.lab and api-int.clustername.example.lab
    ingress_vip: 172.90.12.243 # the IP address to be used for *.apps.clustername.example.lab

    ## Allocate virtual IPs via DHCP server. Equivalent to the vip_dhcp_allocation configuration option of Assisted Installer
    vip_dhcp_allocation: false

    # The subnet on which all nodes are (or will be) accessible.
    machine_network_cidr: 172.90.12.0/24

    # The IP address pool to use for service IP addresses
    service_network_cidr: 172.30.0.0/16

    # Cluster network settings. You are unlikely to need to change these
    cluster_network_cidr: 10.128.0.0/14 # The subnet, internal to the cluster, on which pods will be assigned IPs
    cluster_network_host_prefix: 23 # The subnet prefix length to assign to each individual node.

    # # Cluster network provider. Cannot be changed after cluster is created.
    # # The default is OpenShift SDN unless otherwise specified.
    # network_type: OVNKubernetes
    # network_type: OpenShiftSDN
    network_type: OVNKubernetes
    populate_operator_catalog: true
    mirror_packages:
      - advanced-cluster-management
      - local-storage-operator
      - odf-operator
      - openshift-gitops-operator
      - loki-operator
      - kiali-ossm
      - jaeger-product
      - servicemeshoperator
      - netobserv-operator
      - ptp-operator
      - sriov-network-operator

    os_images:
      - openshift_version: '4.13'
        cpu_architecture: x86_64
        url: http://{{ hostvars['http_store']['ansible_host'] }}/discovery/rhcos-4.13.10-x86_64-live.x86_64.iso
        rootfs_url: http://{{ hostvars['http_store']['ansible_host'] }}/discovery/rhcos-4.13.10-x86_64-live-rootfs.x86_64.img
        version: 413.92.202308210212-0

    release_images:
      - openshift_version: '4.13'
        cpu_architecture: x86_64
        url: registry.nec.nfvi.localdomain:5000/ocp4/openshift4:4.13.10-x86_64
        version: 4.13.10

    assisted_service_image_repo_url: registry.nec.nfvi.localdomain:5000/ocpmetal
    ignore_cached_image_hash_file: true

    listen_address: 172.90.12.241


    ######################################
    # Prerequisite Service Configuration #
    ######################################

    # Proxy settings. These settings apply to: Assisted Installer, Day1 clusters and Day2 clusters.
    # This assumes the host where the AI runs and the OpenShift cluster share the same proxy settings.
    # http_proxy: ""
    # https_proxy: ""
    # no_proxy: ""

    # Flags to enable/disable prerequisite service setup
    # You will need to ensure alternatives are available for anything that will not be automatically set up
    setup_ntp_service: false
    setup_dns_service: true
    setup_pxe_service: false
    setup_registry_service: false # Only required for a Restricted Network installation
    setup_http_store_service: true
    setup_assisted_installer: true # default is true you may wish to turn it off if multiple users are using the same instance.


    # NTP Service
    # ntp_server is the address at which the NTP service is (or will be) available
    ntp_server: 172.90.12.210
    # ntp_server_allow is the range of IPs the NTP service will respond to
    ntp_server_allow: 172.90.12.0/24 # not required if setup_ntp_service is false


    # Mirror Registry Service parameters for a Restricted Network installation

    # use_local_mirror_registry controls if the install process uses a local container registry (mirror_registry) or not.
    # Set this to true to use the mirror registry service set up when `setup_registry_service` is true.
    use_local_mirror_registry: true

    # HTTP Store Configuration
    # ISO name must include the `discovery` directory if you have a SuperMicro machine
    discovery_iso_name: "discovery/{{ cluster_name }}/discovery-image.iso"

    # discovery_iso_server must be discoverable from all BMCs in order for them to mount the ISO hosted there.
    # It is usually necessary to specify different values for KVM nodes and/or physical BMCs if they are on different subnets.
    discovery_iso_server: "http://{{ hostvars['http_store']['ansible_host'] }}"

    ############################
    # Local File Configuration #
    ############################

    path_base_dir: /playbook/

    repo_root_path: "{{ path_base_dir }}/crucible" # path to repository root

    # Directory in which created/updated artifacts are placed
    fetched_dest: "{{ repo_root_path }}/fetched"

    # Configure possible paths for the pull secret
    # first one found will be used
    # note: paths should be absolute
    pull_secret_lookup_paths:
      - "{{ fetched_dest }}/pull-secret.txt"
      - "{{ repo_root_path }}/pull-secret.txt"

    # Configure possible paths for the ssh public key used for debugging
    # first one found will be used
    # note: paths should be absolute
    ssh_public_key_lookup_paths:
      - "{{ fetched_dest }}/ssh_keys/{{ cluster_name }}.pub"
      - "{{ repo_root_path }}/ssh_public_key.pub"
      - ~/.ssh/id_rsa.pub

    # Set the base directory to store ssh keys
    ssh_key_dest_base_dir: "{{ path_base_dir }}"
    # The retrieved cluster kubeconfig will be placed on the bastion host at the following location
    kubeconfig_dest_dir: "{{ path_base_dir }}"
    kubeconfig_dest_filename: "{{ cluster_name }}-kubeconfig"
    kubeadmin_dest_filename: "{{ cluster_name }}-kubeadmin.vault.yml"
    # You can comment out the line below if you want the kubeadmin credentials to be stored in plain text
    # kubeadmin_vault_password_file_path: "{{ repo_root_path }}/kubeadmin_vault_password_file"

    ############################
    #    LOGIC: DO NOT TOUCH   #
    # vvvvvvvvvvvvvvvvvvvvvvvv #
    ############################

    # pull secret logic, no need to change. Configure above
    local_pull_secret_path: "{{ lookup('first_found', pull_secret_lookup_paths) }}"
    pull_secret: "{{ lookup('file', local_pull_secret_path) }}"

    # ssh key logic, no need to change. Configure above
    local_ssh_public_key_path: "{{ lookup('first_found', ssh_public_key_lookup_paths) }}"
    ssh_public_key: "{{ lookup('file', local_ssh_public_key_path) }}"

    # provided mirror certificate logic, no need to change.
    local_mirror_certificate_path: "{{ (setup_registry_service == true) | ternary(
        fetched_dest + '/' + (hostvars['registry_host']['cert_file_prefix'] | default('registry')) + '.crt',
        repo_root_path + '/mirror_certificate.txt')
      }}"
    mirror_certificate: "{{ lookup('file', local_mirror_certificate_path) }}"

    openshift_version: "{{ openshift_full_version.split('.')[:2] | join('.') }}"

    is_valid_single_node_openshift_config: "{{ (groups['nodes'] | length == 1) and (groups['masters'] | length == 1) }}"

    ############################
    # ^^^^^^^^^^^^^^^^^^^^^^^^ #
    #    LOGIC: DO NOT TOUCH   #
    ############################


  children:
    bastions: # n.b. Currently only a single bastion is supported
      hosts:
        bastion:
          ansible_host:  172.90.12.241 # Must be reachable from the Ansible control node

    # Configuration and access information for the pre-requisite services
    # TODO: document differences needed for already-deployed and auto-deployed
    services:
      hosts:
        assisted_installer:
          ansible_host: 172.90.12.241
          host: 172.90.12.241
          port: 8090 # Do not change
          dns_servers:
            - 172.90.12.241

        registry_host:
          ansible_host: 172.90.12.241
          registry_port: 5000
          registry_fqdn: registry.nec.nfvi.localdomain # use in case of different FQDN for the cert
          registry_namespace: ocp4 # This is the default, use only in case the registry namespace name is different
          registry_image: openshift4 # This is the default, use only in case the registry image name is different
          cert_common_name: "{{ registry_fqdn }}"
          cert_country: US
          cert_locality: Raleigh
          cert_organization: Red Hat, Inc.
          cert_organizational_unit: Lab
          cert_state: NC

          # Configure the following secret values in the inventory.vault.yml file
          REGISTRY_HTTP_SECRET: "{{ VAULT_REGISTRY_HOST_REGISTRY_HTTP_SECRET | mandatory }}"
          disconnected_registry_user: "{{ VAULT_REGISTRY_HOST_DISCONNECTED_REGISTRY_USER | mandatory }}"
          disconnected_registry_password: "{{ VAULT_REGISTRY_HOST_DISCONNECTED_REGISTRY_PASSWORD | mandatory }}"

        dns_host:
          ansible_host: 172.90.12.241
          # upstream_dns: 8.8.8.8 # an optional upstream dns server
          # The following are required for DHCP setup
          # use_dhcp: true
          # use_pxe: false
          # dhcp_range_first: 10.60.0.101
          # dhcp_range_last:  10.60.0.105
          # prefix: 24
          # gateway: 10.60.0.1

        http_store:
          ansible_host: 172.90.12.241

        tftp_host:
          ansible_host: 172.90.12.241
          tftp_directory: /var/lib/tftpboot/

        ntp_host:
          ansible_host: 172.90.12.241

    vm_hosts:
      hosts:
        vm_host1: # Required for using "KVM" nodes, ignored if not.
          ansible_user: root
          ansible_host: 172.90.12.241
          host_ip_keyword: ansible_host # the varname in the KVM node hostvars which contains the *IP* of the VM
          images_dir: "/var/lib/libvirt/images/" # directory where qcow images will be placed.
          vm_bridge_ip: 172.90.12.241 # IP for the bridge between VMs and machine network
          vm_bridge_name: caas-br
          SETUP_VM_BRIDGE: false
          vm_bridge_interface: bond0.902 # Interface to be connected to the bridge. DO NOT use your primary interface.
          dns: 172.90.12.241 # DNS used by the bridge
          # ssl cert configuration
          # sushy_fqdn: ... # use in case of different FQDN for the cert
          cert_vars_host_var_key: registry_host # Look up cert values from another host by name (excluding cert_common_name)
          # or
          # cert_country: US
          # cert_locality: Raleigh
          # cert_organization: Red Hat, Inc.
          # cert_organizational_unit: Lab
          # cert_state: NC

        vm_host2: # Required for using "KVM" nodes, ignored if not.
          ansible_user: root
          ansible_host: 172.90.12.141
          host_ip_keyword: ansible_host # the varname in the KVM node hostvars which contains the *IP* of the VM
          images_dir: "/var/lib/libvirt/images/" # directory where qcow images will be placed.
          vm_bridge_ip: 172.90.12.141 # IP for the bridge between VMs and machine network
          vm_bridge_name: caas-br
          SETUP_VM_BRIDGE: false
          vm_bridge_interface: bond0.902 # Interface to be connected to the bridge. DO NOT use your primary interface.
          cert_vars_host_var_key: registry_host # Look up cert values from another host by name (excluding cert_common_name)
          dns: 172.90.12.241


    # Describe the desired cluster members
    nodes:
      # A minimum of three master nodes are required. More are supported.
      # Worker nodes are not required, but if present there must be two or more.
      #
      # Node Required Vars:
      # - role
      #     - Must be either "master" or "worker", and must match the group
      #
      # - mac
      #     - The MAC address of the node, used as a hardware identifier by Assisted Installer.
      #     - The value set here will be used when creating VMs and must be unique within the network.
      #
      # - vendor
      #     - One of "Dell", "HPE", "Lenovo", "SuperMicro", "KVM", "PXE" as the supported BMC APIs.
      #     - "KVM" identifies a node as a VM to be created. If a "KVM" node is present,
      #       then a "vm_host" must be defined in the node and a host with that name must exist
      #       inside the "vm_hosts" group.
      #     - "PXE" identifies a node as a baremetal that needs to boot from PXE.
      #
      # - bmc_address
      # - bmc_user
      # - bmc_password
      #     - details for the BMC that controls the node.
      #     - Must be set to the vm_host for "KVM" nodes.
      #
      # Static IP Vars:
      #   See docs/inventory.md: Network configuration section
      #
      # Optional Vars:
      # - vm_spec
      #     - Specifications for the node:
      #          - cpu_cores
      #          - ram_mib
      #          - disk_size_gb
      #
      # - installation_disk_path
      #     - The value set here will be used by Assisted Installer as the installation disk device
      #       for a given host.
      #     - The value must be a path to the disk device, e.g. /dev/sda
      #     - If not specified, Assisted Installer will pick the first enumerated disk device for a
      #       given host.
      vars:
        # Set the login information for any BMCs. Note that these will be SET on the vm_host virtual BMC.
        bmc_user: "{{ VAULT_NODES_BMC_USER | mandatory }}"
        bmc_password: "{{ VAULT_NODES_BMC_PASSWORD | mandatory }}"
        dns1: "172.90.12.241"
        gateway: "172.90.12.254"
        mask: 24
        network_config:
          dns_server_ips:
            - "{{ dns1 }}"
          interfaces:
            -
              addresses:
                ipv4:
                  -
                    ip: "{{ ansible_host }}"
                    prefix: "{{ mask }}"
              dhcp: false
              mac: "{{ mac }}"
              name: enp1s0
              state: up
              type: ethernet
          routes:
            -
              address: "{{ gateway }}"
              destination: 0.0.0.0/0
              interface: enp1s0
      children:
        masters:
          vars:
            role: master
            vendor: KVM # this example is a virtual control plane
            bmc_address: "172.90.12.241:8082" # port can be changed using sushy_tools_port on the vm_host
            vm_host: vm_host1
            vm_spec:
              cpu_cores: 18
              ram_mib: 40960
              disk_size_gb: 120
          hosts:
            master-super1:
              ansible_host: 172.90.12.244
              mac: "DE:AD:BE:EF:C0:2C"
              installation_disk_path: /dev/vda

              # # Uncomment to set custom BMC credentials for the node
              # # These variables must be set in the inventory.vault.yml file
              # bmc_user: "{{ VAULT_NODES_SUPER1_BMC_USER | mandatory }}"
              # bmc_password: "{{ VAULT_NODES_SUPER1_BMC_PASSWORD | mandatory }}"

            master-super2:
              ansible_host: 172.90.12.245
              mac: "DE:AD:BE:EF:C0:2D"
              installation_disk_path: /dev/vda

            master-super3:
              ansible_host: 172.90.12.246
              mac: "DE:AD:BE:EF:C0:2E"
              installation_disk_path: /dev/vda

        workers:
          vars:
            role: worker
            vendor: KVM # this example is a virtual control plane
            bmc_address: "172.90.12.141:8082" # port can be changed using sushy_tools_port on the vm_host
            vm_host: vm_host2
            vm_spec:
              cpu_cores: 16
              ram_mib: 40960
              disk_size_gb: 120
          hosts:
            ocs-worker1:
              ansible_host: 172.90.12.247
              mac: "DE:AD:BE:EF:C0:1C"

              # # Uncomment to set custom BMC credentials for the node
              # # These variables must be set in the inventory.vault.yml file
              # bmc_user: "{{ VAULT_NODES_SUPER1_BMC_USER | mandatory }}"
              # bmc_password: "{{ VAULT_NODES_SUPER1_BMC_PASSWORD | mandatory }}"
              installation_disk_path: /dev/vda

            ocs-worker2:
              ansible_host: 172.90.12.248
              mac: "DE:AD:BE:EF:C0:1D"
              installation_disk_path: /dev/vda


            ocs-worker3:
              ansible_host: 172.90.12.249
              mac: "DE:AD:BE:EF:C0:1E"
              installation_disk_path: /dev/vda
```

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.
