### ISSUE TITLE
Allow Hybrid worker nodes

### ISSUE THREAD

**Issue by gojeaqui** [redhat-partner-solutions/crucible#285]
### Feature description

Hello,

I would like to propose the option to have a second group of worker nodes with the ability to specify a different vendor and different `network_config` settings.

The use case is (for example) we have a cluster with bare metal worker nodes who have bonding in their interfaces and can be configured using BMC.
But we also have virtual infra nodes who have only one interface and are VMWare pre provissioned VMs which we will use `vendor: PXE`

Something like this:
```
      children:
        masters:
          vars:
            role: master
            vendor: PXE

        workers:
          vars:
            role: worker
            vendor: PXE

        workers2:
          vars:
            role: worker
            vendor: Dell # This example uses baremetal worker nodes
```

### Required statements

- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by nocturnalastro** [comment]
You can have sub groups under workers ansible should handle that fine.

```yaml
children:
    masters:
        vars:
            role: master
            vendor: PXE
        hosts: 
           ...
    workers:
        vars:
            role: worker
        children:
            infra_workers:
                vars: 
                    vendor: PXE
                hosts: 
                    worker1:
                        ...
            metal_workers:
                vars: 
                    vendor: Dell
                hosts:
                    worker2:
                        ...
```
